defaults:
  - _self_
  - env: jenga
  - encoder: dino 
  - action_encoder: proprio
  - proprio_encoder: proprio
  - decoder: vqvae
  - predictor: vit
  - override hydra/launcher: submitit_slurm

# base path to save model outputs. Checkpoints will be saved to ${ckpt_base_path}/outputs.
ckpt_base_path: ./ # put absolute path here

hydra:
  run:
    dir: ${ckpt_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${ckpt_base_path}/outputs/2026-03-08/01-49-09/
  sweep:
    dir: ${ckpt_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # dir: ${ckpt_base_path}/outputs/2026-03-08/01-49-09
    # subdir: ${hydra.job.num}
    subdir: ${hydra.job.num}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    nodes: 1
    tasks_per_node: 4
    cpus_per_task: 8
    mem_gb: 256
    # mem_gb: 64
    gres: "gpu:h100:4"
    # gres: "gpu:1"

    timeout_min: 1440
    # timeout_min: 20
    additional_parameters:
      mail-user: "a2budhwa@uwaterloo.ca"
      mail-type: "BEGIN,END,FAIL"
      account: "def-soojeon"
    # --------------------------
    
    setup: 
          - "module --force purge"
          - "module load StdEnv/2023 python/3.11.5 cuda/12.2 cudnn/8.9.5.29 opencv/4.9.0 mujoco/3.3.0"
          # - "module load StdEnv/2023 python/3.11.5 cuda/12.9 cudnn/9.13.1.26 opencv/4.9.0 mujoco/3.3.0"
          - "source /home/ali313/scratch/dino_wm/vdino/bin/activate"
          - "export DEBUGVAR=$(scontrol show hostnames $SLURM_JOB_NODELIST)"
          - 'export MASTER_ADDR="$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)"'
          - "export MASTER_PORT=$(shuf -i 20000-65000 -n 1)"
          - 'export WANDB_API_KEY="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"'
          - "export NCCL_ASYNC_ERROR_HANDLING=1"
          - "export TORCH_DISTRIBUTED_DEBUG=DETAIL" # Gives more info if it happens again
          - "export TORCH_NCCL_BLOCKING_WAIT=1"
          - "export OMP_NUM_THREADS=1"
          - "export MKL_NUM_THREADS=1"
          - "export OPENCV_FORK_HANDLING_IS_DANGEROUS=1"
          - "export NCCL_BLOCKING_WAIT=1"
          - "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"
          - "export CUDA_VISIBLE_DEVICES=$SLURM_LOCALID" # Forces each task to its own GPU
          

training:
  seed: 0
  epochs: 100
  batch_size: 32 # should >= nodes * tasks_per_node
  save_every_x_epoch: 5
  reconstruct_every_x_batch: 500
  num_reconstruct_samples: 2
  encoder_lr: 1e-6
  decoder_lr: 3e-4
  predictor_lr: 5e-5
  action_encoder_lr: 5e-4
  dist_timeout: 1800

# img_size: 224 # should be a multiple of 224
img_size: 224 # should be a multiple of 224

frameskip: 1
concat_dim: 1

normalize_action: True

# action encoder
action_emb_dim: 10
num_action_repeat: 1

# proprio encoder
proprio_emb_dim: 10
num_proprio_repeat: 1

num_views: 2

num_hist: 3
num_pred: 1 # only supports 1
has_predictor: True # set this to False for only training a decoder
has_decoder: True # set this to False for only training a predictor

model:
  _target_: models.dual_visual_world_model.VWorldModel
  image_size: ${img_size}
  num_hist: ${num_hist}
  num_pred: ${num_pred}
  train_encoder: False
  train_predictor: True
  train_decoder: True
  decoder_front: ${decoder}
  decoder_wrist: ${decoder}
  # decoder_front: None
  # decoder_wrist: None

debug: False 

# Planning params for planning eval jobs launched during training
plan_settings: 
  # plan_cfg_path: conf/plan.yaml # set to null for no planning evals
  plan_cfg_path: null 
  planner: ['gd', 'cem']
  goal_source: ['dset', 'random_state']
  goal_H: [5]
  alpha: [0.1, 1]