name: jenga_single
args: []
kwargs: 
  object_name: "jenga_single"

load_dir: ""

dataset:
  _target_: "datasets.jenga_dset_single.load_jenga_slice_train_val"
  n_rollout: null 
  normalize_action: ${normalize_action}
  data_path: "/home/corey/data/jenga_mujoco_noise"
  
  cam_prefixes: ["cam2"] # Strictly request single camera

  split_ratio: 0.9
  action_freq: 10
  img_freq: 30
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 4