name: jenga
args: []
kwargs: 
  object_name: "jenga"

load_dir: ""

dataset:
  _target_: "datasets.jenga_dset.load_jenga_slice_train_val"
  n_rollout: null 
  normalize_action: ${normalize_action}
  # data_path: "/mnt/diffusion_policy/tasks/pick_place/dual_wrist/world_model/"
  data_path: "/home/sanger/world_model"

  split_ratio: 0.9
  # These are now critical for the 3x pairing logic
  action_freq: 10
  img_freq: 30
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 4  